# Remove '#' to select a file.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[files]
# "README.md" = "selected"
# "package-lock.json" = "selected"
# "package.json" = "selected"
# prompt = "selected"
# "public/favicon.ico" = "selected"
# "public/index.html" = "selected"
# "public/logo512.png" = "selected"
# "public/manifest.json" = "selected"
# "public/robots.txt" = "selected"
# "public/logo192.png" = "selected"
# "build/favicon.ico" = "selected"
# "build/index.html" = "selected"
# "build/logo512.png" = "selected"
# "build/asset-manifest.json" = "selected"
# "build/manifest.json" = "selected"
# "build/robots.txt" = "selected"
# "build/logo192.png" = "selected"
# "build/static/css/main.72d24341.css.map" = "selected"
# "build/static/css/main.72d24341.css" = "selected"
# "build/static/js/787.4ffd4c9f.chunk.js.map" = "selected"
# "build/static/js/main.600eb1a0.js.LICENSE.txt" = "selected"
# "build/static/js/main.600eb1a0.js.map" = "selected"
# "build/static/js/787.4ffd4c9f.chunk.js" = "selected"
# "build/static/js/main.600eb1a0.js" = "selected"
# "build/static/media/cognitive-control-autonomous-vehicles.3eb8404ea063b3cba086.jpg" = "selected"
# "build/static/media/project2.351b725b857f381bdf40.png" = "selected"
# "build/static/media/accessible-data-science-image.591c4615095ad463a2d4.jpg" = "selected"
# "build/static/media/cognitive-model-ai-image.ae5850b1c5807e72b338.jpg" = "selected"
# "build/static/media/brice.0b1f142ce1c26c5f4d9a.png" = "selected"
# "build/static/media/logo.4f1047199ba668267b8d.png" = "selected"
# "build/static/media/about-section-header-image.5a4d8198c2ea48deb4a8.jpg" = "selected"
# "build/static/media/athena.48d14acecfd6000a3d57.jpeg" = "selected"
# "build/static/media/accessible-data-science.979330e44f9da138d3c3.png" = "selected"
# "build/static/media/sustainable-software-image.5d5a560abee0d0d94c56.jpg" = "selected"
# "build/static/media/philipp.b3dbad8848528f19ef3c.jpeg" = "selected"
# "build/static/media/run.103afc93b894184cfd69.png" = "selected"
# "build/static/media/codebase-synthesis-evaluation.98c7afa79bc9c008b276.jpeg" = "selected"
# "build/static/media/rini.72568d7ff3d332632199.jpg" = "selected"
# "build/static/media/default-user.fd9c6e7271b20d7adbd4.png" = "selected"
# "build/static/media/david.7f2a2916dc2790950bda.png" = "selected"
# "build/static/media/katie.660e3a1ba8c44e28a663.jpeg" = "selected"
# "build/static/media/cognitive-bias-and-development.8c9523bde26906ab72f4.png" = "selected"
# "build/static/media/stackoverflow.0123b8df35f2e7d20bc8.png" = "selected"
# "build/static/media/sustainablePlaceholder1.13c4234317edde1849b7.png" = "selected"
# "build/static/media/project1.ee0b2f11cdcdfec10229.png" = "selected"
# "src/reportWebVitals.js" = "selected"
# "src/App.css" = "selected"
# "src/index.js" = "selected"
# "src/index.css" = "selected"
# "src/App.test.js" = "selected"
# "src/setupTests.js" = "selected"
# "src/logo.svg" = "selected"
# "src/App.js" = "selected"
# "src/img/david.png" = "selected"
# "src/img/default-user.png" = "selected"
# "src/img/brice.png" = "selected"
# "src/img/project3.png" = "selected"
# "src/img/codebase-synthesis-evaluation.jpeg" = "selected"
# "src/img/external_link.png" = "selected"
# "src/img/cognitive-control-autonomous-vehicles.jpg" = "selected"
# "src/img/sadra.jpeg" = "selected"
# "src/img/project2.png" = "selected"
# "src/img/accessible-data-science.png" = "selected"
# "src/img/project1.png" = "selected"
# "src/img/about-section-header-image.jpg" = "selected"
# "src/img/athena.jpeg" = "selected"
# "src/img/cognitive-model-ai-image.jpg" = "selected"
# "src/img/rini.jpg" = "selected"
# "src/img/philipp.jpeg" = "selected"
# "src/img/sustainablePlaceholder1.png" = "selected"
# "src/img/run.png" = "selected"
# "src/img/katie.jpeg" = "selected"
# "src/img/logo.png" = "selected"
# "src/img/accessible-data-science-image.jpg" = "selected"
# "src/img/about-section-header-image-1.jpg" = "selected"
# "src/img/stackoverflow.png" = "selected"
# "src/img/about-section-header-image-2.jpg" = "selected"
# "src/img/sustainable-software-image.jpg" = "selected"
# "src/img/cognitive-bias-and-development.png" = "selected"
# "src/components/Profile.js" = "selected"
# "src/components/AboutSection.js" = "selected"
# "src/components/Header.js" = "selected"
# "src/components/PeopleSection.js" = "selected"
# "src/components/ProjectsSection.js" = "selected"
# "src/components/Project.js" = "selected"
# "src/components/Project.css" = "selected"
# "src/components/Header.css" = "selected"
# "src/components/MainSection.js" = "selected"
# "src/components/Footer.js" = "selected"
# "src/components/Profile.css" = "selected"
